[package]
name = "clik"
version = "0.0.1"
edition = "2021"
description = "A simple-to-use interactive CLI framework"
readme = "README.md"
repository = "https://github.com/maxkofler/clik"
license = "MIT"
keywords = ["cli", "interactive"]
include = ["/src/**.rs", "/README.md", "/LICENSE"]

[dependencies]
async-recursion = "1.0.5"

[dev-dependencies]
rustyline = "12.0.0"
